rvm:
  - 2.7
  - 2.6
  - 2.5
  - jruby
  - ruby-head

matrix:
  allow_failures:
    -
      rvm: jruby
    -
      rvm: ruby-head

gemfile:
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_4.2_sprockets4.gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.0_sprockets4.gemfile
  - gemfiles/rails_6.0.gemfile
  - gemfiles/rails_head.gemfile
  - gemfiles/rails_head_sprockets4.gemfile
