rvm:
  - 2.2.2
  - jruby-19mode
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
    - gemfile: gemfiles/rails_head.gemfile

gemfile:
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_head.gemfile
