rvm:
  - 2.3.1
  - 2.2.2
  - jruby-9.1.0.0
  - ruby-head

matrix:
  allow_failures:
    -
      rvm: jruby-9.1.0.0
      gemfile: gemfiles/rails_5.0.gemfile
    -
      rvm: jruby-9.1.0.0
      gemfile: gemfiles/rails_head.gemfile
    -
      rvm: ruby-head

gemfile:
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_head.gemfile
